version: '3.8'

services:
  # O seu Backend Java (Spring Boot)
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - rede-saas

  # O seu Frontend (Angular/Web)
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rede-saas

networks:
  rede-saas:
    driver: bridge